#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from re import sub
from sys import argv, path, exit
from os.path import realpath, abspath, dirname, join

__dir__ = dirname(realpath(__file__))
src = abspath(join(__dir__, '..', 'src'))
path.insert(0, src)

from tfadm.__main__ import main

if __name__ == '__main__':
  argv[0] = sub(r'(-script\.pyw|\.exe)?$', '', argv[0])
  exit(main())
